#############################################################################
# Makefile for building: bin/Elements.app/Contents/MacOS/Elements
# Generated by qmake (3.0) (Qt 5.2.0)
# Project:  Elements.pro
# Template: app
# Command: /Users/Marcus/Qt5.2.0/5.2.0/clang_64/bin/qmake -o Makefile Elements.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_NO_DEBUG -DQT_QUICK_LIB -DQT_QML_LIB -DQT_WIDGETS_LIB -DQT_NETWORK_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk -mmacosx-version-min=10.7 -Wall -W -fPIE $(DEFINES)
CXXFLAGS      = -pipe -O2 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk -std=c++11 -stdlib=libc++ -mmacosx-version-min=10.7 -Wall -W -fPIE $(DEFINES)
INCPATH       = -I../../Qt5.2.0/5.2.0/clang_64/mkspecs/macx-clang -I. -I../../Qt5.2.0/5.2.0/clang_64/lib/QtQuick.framework/Versions/5/Headers -I../../Qt5.2.0/5.2.0/clang_64/lib/QtQml.framework/Versions/5/Headers -I../../Qt5.2.0/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers -I../../Qt5.2.0/5.2.0/clang_64/lib/QtNetwork.framework/Versions/5/Headers -I../../Qt5.2.0/5.2.0/clang_64/lib/QtGui.framework/Versions/5/Headers -I../../Qt5.2.0/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers -Imoc -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/System/Library/Frameworks/OpenGL.framework/Versions/A/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/System/Library/Frameworks/AGL.framework/Headers -F/Users/Marcus/Qt5.2.0/5.2.0/clang_64/lib
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk -stdlib=libc++ -mmacosx-version-min=10.7
LIBS          = $(SUBLIBS) -F/Users/Marcus/Qt5.2.0/5.2.0/clang_64/lib -framework QtQuick -framework QtQml -framework QtNetwork -framework QtCore -framework QtGui -framework QtWidgets -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
QMAKE         = /Users/Marcus/Qt5.2.0/5.2.0/clang_64/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = debug/

####### Files

SOURCES       = src/main.cpp \
		src/Engine.cpp \
		src/Debug.cpp \
		src/DataHandler.cpp \
		src/openglwindow.cpp qrc_GUI.cpp \
		moc/moc_Engine.cpp \
		moc/moc_DataHandler.cpp \
		moc/moc_openglwindow.cpp
OBJECTS       = debug/main.o \
		debug/Engine.o \
		debug/Debug.o \
		debug/DataHandler.o \
		debug/openglwindow.o \
		debug/qrc_GUI.o \
		debug/moc_Engine.o \
		debug/moc_DataHandler.o \
		debug/moc_openglwindow.o
DIST          = ../../Qt5.2.0/5.2.0/clang_64/mkspecs/features/spec_pre.prf \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/qdevice.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/features/device_config.prf \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/common/shell-unix.conf \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/common/unix.conf \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/common/mac.conf \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/common/macx.conf \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/common/gcc-base.conf \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/common/clang.conf \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/common/clang-mac.conf \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/qconfig.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/features/qt_functions.prf \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/features/qt_config.prf \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/macx-clang/qmake.conf \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/features/exclusive_builds.prf \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/features/default_pre.prf \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/features/mac/default_pre.prf \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/features/resolve_config.prf \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/features/default_post.prf \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/features/c++11.prf \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/features/mac/sdk.prf \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/features/mac/default_post.prf \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/features/mac/objective_c.prf \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/features/warn_on.prf \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/features/qt.prf \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/features/resources.prf \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/features/moc.prf \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/features/unix/opengl.prf \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/features/uic.prf \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/features/unix/thread.prf \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/features/mac/rez.prf \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/features/testcase_targets.prf \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/features/exceptions.prf \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/features/yacc.prf \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/features/lex.prf \
		Elements.pro \
		resources/GUI.qrc \
		Elements.pro
QMAKE_TARGET  = Elements
DESTDIR       = bin/#avoid trailing-slash linebreak
TARGET        = bin/Elements.app/Contents/MacOS/Elements

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-O2 \
		-isysroot \
		/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk \
		-std=c++11 \
		-stdlib=libc++ \
		-mmacosx-version-min=10.7 \
		-Wall \
		-W



first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile bin/Elements.app/Contents/PkgInfo bin/Elements.app/Contents/Resources/empty.lproj bin/Elements.app/Contents/Info.plist $(TARGET)

$(TARGET):  $(OBJECTS)  
	@test -d bin/Elements.app/Contents/MacOS/ || mkdir -p bin/Elements.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Elements.pro ../../Qt5.2.0/5.2.0/clang_64/mkspecs/macx-clang/qmake.conf ../../Qt5.2.0/5.2.0/clang_64/mkspecs/features/spec_pre.prf \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/qdevice.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/features/device_config.prf \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/common/shell-unix.conf \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/common/unix.conf \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/common/mac.conf \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/common/macx.conf \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/common/gcc-base.conf \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/common/clang.conf \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/common/clang-mac.conf \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/qconfig.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/features/qt_functions.prf \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/features/qt_config.prf \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/macx-clang/qmake.conf \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/features/exclusive_builds.prf \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/features/default_pre.prf \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/features/mac/default_pre.prf \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/features/resolve_config.prf \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/features/default_post.prf \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/features/c++11.prf \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/features/mac/sdk.prf \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/features/mac/default_post.prf \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/features/mac/objective_c.prf \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/features/warn_on.prf \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/features/qt.prf \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/features/resources.prf \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/features/moc.prf \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/features/unix/opengl.prf \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/features/uic.prf \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/features/unix/thread.prf \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/features/mac/rez.prf \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/features/testcase_targets.prf \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/features/exceptions.prf \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/features/yacc.prf \
		../../Qt5.2.0/5.2.0/clang_64/mkspecs/features/lex.prf \
		Elements.pro \
		resources/GUI.qrc \
		/Users/Marcus/Qt5.2.0/5.2.0/clang_64/lib/QtQuick.framework/QtQuick.prl \
		/Users/Marcus/Qt5.2.0/5.2.0/clang_64/lib/QtQml.framework/QtQml.prl \
		/Users/Marcus/Qt5.2.0/5.2.0/clang_64/lib/QtNetwork.framework/QtNetwork.prl \
		/Users/Marcus/Qt5.2.0/5.2.0/clang_64/lib/QtCore.framework/QtCore.prl \
		/Users/Marcus/Qt5.2.0/5.2.0/clang_64/lib/QtGui.framework/QtGui.prl \
		/Users/Marcus/Qt5.2.0/5.2.0/clang_64/lib/QtWidgets.framework/QtWidgets.prl
	$(QMAKE) -o Makefile Elements.pro
../../Qt5.2.0/5.2.0/clang_64/mkspecs/features/spec_pre.prf:
../../Qt5.2.0/5.2.0/clang_64/mkspecs/qdevice.pri:
../../Qt5.2.0/5.2.0/clang_64/mkspecs/features/device_config.prf:
../../Qt5.2.0/5.2.0/clang_64/mkspecs/common/shell-unix.conf:
../../Qt5.2.0/5.2.0/clang_64/mkspecs/common/unix.conf:
../../Qt5.2.0/5.2.0/clang_64/mkspecs/common/mac.conf:
../../Qt5.2.0/5.2.0/clang_64/mkspecs/common/macx.conf:
../../Qt5.2.0/5.2.0/clang_64/mkspecs/common/gcc-base.conf:
../../Qt5.2.0/5.2.0/clang_64/mkspecs/common/gcc-base-mac.conf:
../../Qt5.2.0/5.2.0/clang_64/mkspecs/common/clang.conf:
../../Qt5.2.0/5.2.0/clang_64/mkspecs/common/clang-mac.conf:
../../Qt5.2.0/5.2.0/clang_64/mkspecs/qconfig.pri:
../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_core.pri:
../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_declarative.pri:
../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_declarative_private.pri:
../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_designer.pri:
../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_gui.pri:
../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_help.pri:
../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_network.pri:
../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_qml.pri:
../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_quick.pri:
../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_script.pri:
../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_script_private.pri:
../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_sql.pri:
../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_svg.pri:
../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_webkit.pri:
../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_webkit_private.pri:
../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_xml.pri:
../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../Qt5.2.0/5.2.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../Qt5.2.0/5.2.0/clang_64/mkspecs/features/qt_functions.prf:
../../Qt5.2.0/5.2.0/clang_64/mkspecs/features/qt_config.prf:
../../Qt5.2.0/5.2.0/clang_64/mkspecs/macx-clang/qmake.conf:
../../Qt5.2.0/5.2.0/clang_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../../Qt5.2.0/5.2.0/clang_64/mkspecs/features/exclusive_builds.prf:
../../Qt5.2.0/5.2.0/clang_64/mkspecs/features/default_pre.prf:
../../Qt5.2.0/5.2.0/clang_64/mkspecs/features/mac/default_pre.prf:
../../Qt5.2.0/5.2.0/clang_64/mkspecs/features/resolve_config.prf:
../../Qt5.2.0/5.2.0/clang_64/mkspecs/features/default_post.prf:
../../Qt5.2.0/5.2.0/clang_64/mkspecs/features/c++11.prf:
../../Qt5.2.0/5.2.0/clang_64/mkspecs/features/mac/sdk.prf:
../../Qt5.2.0/5.2.0/clang_64/mkspecs/features/mac/default_post.prf:
../../Qt5.2.0/5.2.0/clang_64/mkspecs/features/mac/objective_c.prf:
../../Qt5.2.0/5.2.0/clang_64/mkspecs/features/warn_on.prf:
../../Qt5.2.0/5.2.0/clang_64/mkspecs/features/qt.prf:
../../Qt5.2.0/5.2.0/clang_64/mkspecs/features/resources.prf:
../../Qt5.2.0/5.2.0/clang_64/mkspecs/features/moc.prf:
../../Qt5.2.0/5.2.0/clang_64/mkspecs/features/unix/opengl.prf:
../../Qt5.2.0/5.2.0/clang_64/mkspecs/features/uic.prf:
../../Qt5.2.0/5.2.0/clang_64/mkspecs/features/unix/thread.prf:
../../Qt5.2.0/5.2.0/clang_64/mkspecs/features/mac/rez.prf:
../../Qt5.2.0/5.2.0/clang_64/mkspecs/features/testcase_targets.prf:
../../Qt5.2.0/5.2.0/clang_64/mkspecs/features/exceptions.prf:
../../Qt5.2.0/5.2.0/clang_64/mkspecs/features/yacc.prf:
../../Qt5.2.0/5.2.0/clang_64/mkspecs/features/lex.prf:
Elements.pro:
resources/GUI.qrc:
/Users/Marcus/Qt5.2.0/5.2.0/clang_64/lib/QtQuick.framework/QtQuick.prl:
/Users/Marcus/Qt5.2.0/5.2.0/clang_64/lib/QtQml.framework/QtQml.prl:
/Users/Marcus/Qt5.2.0/5.2.0/clang_64/lib/QtNetwork.framework/QtNetwork.prl:
/Users/Marcus/Qt5.2.0/5.2.0/clang_64/lib/QtCore.framework/QtCore.prl:
/Users/Marcus/Qt5.2.0/5.2.0/clang_64/lib/QtGui.framework/QtGui.prl:
/Users/Marcus/Qt5.2.0/5.2.0/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile Elements.pro

qmake_all: FORCE

bin/Elements.app/Contents/PkgInfo: 
	@test -d bin/Elements.app/Contents || mkdir -p bin/Elements.app/Contents
	@$(DEL_FILE) bin/Elements.app/Contents/PkgInfo
	@echo "APPL????" >bin/Elements.app/Contents/PkgInfo
bin/Elements.app/Contents/Resources/empty.lproj: 
	@test -d bin/Elements.app/Contents/Resources || mkdir -p bin/Elements.app/Contents/Resources
	@touch bin/Elements.app/Contents/Resources/empty.lproj
	
bin/Elements.app/Contents/Info.plist: 
	@test -d bin/Elements.app/Contents || mkdir -p bin/Elements.app/Contents
	@$(DEL_FILE) bin/Elements.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,Elements,g" -e "s,@TYPEINFO@,????,g" ../../Qt5.2.0/5.2.0/clang_64/mkspecs/macx-clang/Info.plist.app >bin/Elements.app/Contents/Info.plist
dist: 
	@test -d debug/Elements1.0.0 || mkdir -p debug/Elements1.0.0
	$(COPY_FILE) --parents $(SOURCES) $(DIST) debug/Elements1.0.0/ && $(COPY_FILE) --parents resources/GUI.qrc debug/Elements1.0.0/ && $(COPY_FILE) --parents src/Engine.h src/Parameters.h src/Console.h src/Debug.h src/DataHandler.h src/openglwindow.h debug/Elements1.0.0/ && $(COPY_FILE) --parents src/main.cpp src/Engine.cpp src/Debug.cpp src/DataHandler.cpp src/openglwindow.cpp debug/Elements1.0.0/ && (cd `dirname debug/Elements1.0.0` && $(TAR) Elements1.0.0.tar Elements1.0.0 && $(COMPRESS) Elements1.0.0.tar) && $(MOVE) `dirname debug/Elements1.0.0`/Elements1.0.0.tar.gz . && $(DEL_FILE) -r debug/Elements1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) -r bin/Elements.app
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_rcc_make_all: qrc_GUI.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_GUI.cpp
qrc_GUI.cpp: resources/GUI.qrc \
		resources/Tooltip.qml \
		resources/GUI.qml \
		resources/BottomGui.qml \
		resources/TopGui.qml \
		resources/pics/water.png \
		resources/pics/fire.png \
		resources/pics/smoke.png
	/Users/Marcus/Qt5.2.0/5.2.0/clang_64/bin/rcc -name GUI resources/GUI.qrc -o qrc_GUI.cpp

compiler_moc_header_make_all: moc/moc_Engine.cpp moc/moc_DataHandler.cpp moc/moc_openglwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc/moc_Engine.cpp moc/moc_DataHandler.cpp moc/moc_openglwindow.cpp
moc/moc_Engine.cpp: ../../Qt5.2.0/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/QTime \
		../../Qt5.2.0/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/qdatetime.h \
		../../Qt5.2.0/5.2.0/clang_64/lib/QtGui.framework/Versions/5/Headers/QOpenGLFunctions \
		../../Qt5.2.0/5.2.0/clang_64/lib/QtGui.framework/Versions/5/Headers/qopenglfunctions.h \
		src/Parameters.h \
		src/DataHandler.h \
		../../Qt5.2.0/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/QObject \
		../../Qt5.2.0/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/qobject.h \
		src/Debug.h \
		src/Console.h \
		../../Qt5.2.0/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/QTimer \
		../../Qt5.2.0/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/qtimer.h \
		src/Engine.h
	/Users/Marcus/Qt5.2.0/5.2.0/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 $(INCPATH) src/Engine.h -o moc/moc_Engine.cpp

moc/moc_DataHandler.cpp: ../../Qt5.2.0/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/QObject \
		../../Qt5.2.0/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/qobject.h \
		src/Parameters.h \
		src/Debug.h \
		src/Console.h \
		src/DataHandler.h
	/Users/Marcus/Qt5.2.0/5.2.0/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 $(INCPATH) src/DataHandler.h -o moc/moc_DataHandler.cpp

moc/moc_openglwindow.cpp: src/openglwindow.h
	/Users/Marcus/Qt5.2.0/5.2.0/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 $(INCPATH) src/openglwindow.h -o moc/moc_openglwindow.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_header_clean 

####### Compile

debug/main.o: src/main.cpp ../../Qt5.2.0/5.2.0/clang_64/lib/QtGui.framework/Versions/5/Headers/QGuiApplication \
		../../Qt5.2.0/5.2.0/clang_64/lib/QtGui.framework/Versions/5/Headers/qguiapplication.h \
		src/Parameters.h \
		src/Engine.h \
		../../Qt5.2.0/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/QTime \
		../../Qt5.2.0/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/qdatetime.h \
		../../Qt5.2.0/5.2.0/clang_64/lib/QtGui.framework/Versions/5/Headers/QOpenGLFunctions \
		../../Qt5.2.0/5.2.0/clang_64/lib/QtGui.framework/Versions/5/Headers/qopenglfunctions.h \
		src/DataHandler.h \
		../../Qt5.2.0/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/QObject \
		../../Qt5.2.0/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/qobject.h \
		src/Debug.h \
		src/Console.h \
		../../Qt5.2.0/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/QTimer \
		../../Qt5.2.0/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/qtimer.h \
		../../Qt5.2.0/5.2.0/clang_64/lib/QtQml.framework/Versions/5/Headers/QQmlContext \
		../../Qt5.2.0/5.2.0/clang_64/lib/QtQml.framework/Versions/5/Headers/qqmlcontext.h \
		../../Qt5.2.0/5.2.0/clang_64/lib/QtQml.framework/Versions/5/Headers/QQmlEngine \
		../../Qt5.2.0/5.2.0/clang_64/lib/QtQml.framework/Versions/5/Headers/qqmlengine.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o debug/main.o src/main.cpp

debug/Engine.o: src/Engine.cpp ../../Qt5.2.0/5.2.0/clang_64/lib/QtQml.framework/Versions/5/Headers/QQmlContext \
		../../Qt5.2.0/5.2.0/clang_64/lib/QtQml.framework/Versions/5/Headers/qqmlcontext.h \
		../../Qt5.2.0/5.2.0/clang_64/lib/QtQml.framework/Versions/5/Headers/QQmlEngine \
		../../Qt5.2.0/5.2.0/clang_64/lib/QtQml.framework/Versions/5/Headers/qqmlengine.h \
		../../Qt5.2.0/5.2.0/clang_64/lib/QtGui.framework/Versions/5/Headers/QSurfaceFormat \
		../../Qt5.2.0/5.2.0/clang_64/lib/QtGui.framework/Versions/5/Headers/qsurfaceformat.h \
		../../Qt5.2.0/5.2.0/clang_64/lib/QtGui.framework/Versions/5/Headers/QSurface \
		../../Qt5.2.0/5.2.0/clang_64/lib/QtGui.framework/Versions/5/Headers/qsurface.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o debug/Engine.o src/Engine.cpp

debug/Debug.o: src/Debug.cpp src/Debug.h \
		src/Parameters.h \
		src/Console.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o debug/Debug.o src/Debug.cpp

debug/DataHandler.o: src/DataHandler.cpp src/DataHandler.h \
		../../Qt5.2.0/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/QObject \
		../../Qt5.2.0/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/qobject.h \
		src/Parameters.h \
		src/Debug.h \
		src/Console.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o debug/DataHandler.o src/DataHandler.cpp

debug/openglwindow.o: src/openglwindow.cpp src/openglwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o debug/openglwindow.o src/openglwindow.cpp

debug/qrc_GUI.o: qrc_GUI.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o debug/qrc_GUI.o qrc_GUI.cpp

debug/moc_Engine.o: moc/moc_Engine.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o debug/moc_Engine.o moc/moc_Engine.cpp

debug/moc_DataHandler.o: moc/moc_DataHandler.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o debug/moc_DataHandler.o moc/moc_DataHandler.cpp

debug/moc_openglwindow.o: moc/moc_openglwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o debug/moc_openglwindow.o moc/moc_openglwindow.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

